"""Extend sec_hmdb_id and name columns

Revision ID: 5e2842394881
Revises: d041d0c2fb06
Create Date: 2026-04-24 14:17:03.142988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e2842394881'
down_revision: Union[str, Sequence[str], None] = 'd041d0c2fb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hmdb', 'sec_hmdb_id',
               existing_type=sa.VARCHAR(length=275),
               type_=sqlmodel.sql.sqltypes.AutoString(length=300),
               existing_nullable=False)
    op.alter_column('hmdb', 'name',
               existing_type=sa.VARCHAR(length=275),
               type_=sqlmodel.sql.sqltypes.AutoString(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hmdb', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=300),
               type_=sa.VARCHAR(length=275),
               existing_nullable=False)
    op.alter_column('hmdb', 'sec_hmdb_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=300),
               type_=sa.VARCHAR(length=275),
               existing_nullable=False)
    # ### end Alembic commands ###
